<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container66S0pyz\srcApp_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container66S0pyz/srcApp_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/Container66S0pyz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelEnvDebugContainer::class, false)) {
    \class_alias(\Container66S0pyz\srcApp_KernelEnvDebugContainer::class, srcApp_KernelEnvDebugContainer::class, false);
}

return new \Container66S0pyz\srcApp_KernelEnvDebugContainer([
    'container.build_hash' => '66S0pyz',
    'container.build_id' => '24d70669',
    'container.build_time' => 1571233252,
], __DIR__.\DIRECTORY_SEPARATOR.'Container66S0pyz');
