<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'list' => [[], ['_controller' => 'App\\Controller\\ArtistController::index'], [], [['text', '/artist_list']], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'label_page' => [[], ['_controller' => 'App\\Controller\\LabelController::index'], [], [['text', '/label_page']], [], []],
    'ranking' => [[], ['_controller' => 'App\\Controller\\RankingController::index'], [], [['text', '/ranking_news']], [], []],
    'record_page' => [[], ['_controller' => 'App\\Controller\\RecordController::index'], [], [['text', '/record_page']], [], []],
];
