<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZqSRQNS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZqSRQNS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZqSRQNS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZqSRQNS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZqSRQNS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZqSRQNS',
    'container.build_id' => '5e893e87',
    'container.build_time' => 1571409913,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZqSRQNS');
